# Generated by Django 3.2.15 on 2022-09-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainInformations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='soil_id',
            new_name='product_id',
        ),
    ]
