# Generated by Django 3.2.15 on 2022-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainInformations', '0003_auto_20220922_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desease',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
