# Generated by Django 3.2.15 on 2022-09-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainInformations', '0004_alter_desease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desease',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainInformations.des'),
        ),
    ]
